### ISSUE TITLE
Immagine non centrata su layout verticali

### ISSUE THREAD

**Issue by dr-prodigy** [gothrek/GotScraperV2#37]
In caso di layout verticali, l'immagine del layout non è centrata nell'area schermo dell'immagine del cabinato
![Screen Shot 2019-12-18 at 22 16 20](https://user-images.githubusercontent.com/28216945/71124041-4f9a6500-21e4-11ea-9b8a-f1e60ac69922.png)

**Comment by gothrek** [comment]
ora l'immagine a seconda della dimensione viene centrata orizzontalmente
