### ISSUE TITLE
Creare About box

### ISSUE THREAD

**Issue by dr-prodigy** [gothrek/GotScraperV2#43]
Sarebbe corretto inserire un "about box" con nome, codice versione e credits ("by Gothrek")..

**Comment by gothrek** [comment]
tu dici a parte di vederlo nella barra della form?

**Comment by dr-prodigy** [comment]
Si esatto! About box con dati del sw e tuoi

**Comment by gothrek** [comment]
aggiunti credits, con sorpresa!!!
